<a href="https://colab.research.google.com/github/Seungkyu-Han/deep_learning/blob/main/ch4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
y = np.array([0.9, 0.1, 0, 0, 0, 0, 0, 0, 0, 0])
t = np.array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [3]:
def sum_squares_error(x, t):
  return 0.5 * np.sum((y - t) ** 2)

In [4]:
sum_squares_error(y, t)

np.float64(0.009999999999999998)

In [5]:
y = np.array([0.9, 0.1, 0, 0, 0, 0, 0, 0, 0, 0])
t = np.array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [6]:
def cross_entropy_error(y, t):
  delta = 1e-8
  return - np.sum(t * np.log(y + delta))

In [7]:
y = np.array([0.9, 0.1, 0, 0, 0, 0, 0, 0, 0, 0])
t = np.array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [8]:
cross_entropy_error(y, t)

np.float64(0.10536050454671517)

In [9]:
y = np.array([0.1, 0.9, 0, 0, 0, 0, 0, 0, 0, 0])
t = np.array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [10]:
cross_entropy_error(y, t)

np.float64(2.3025849929940505)

In [11]:
import numpy as np

rng = np.random.default_rng()

train = rng.random(1000)

batch_mask = np.random.choice(train.shape[0], 20)

print(batch_mask)

print(train[batch_mask])

[ 88 100 369   1 833 928 437 585 707 221 364 403 950 651 397 376 119 170
 170 288]
[0.28519156 0.56719785 0.41905914 0.30513559 0.85235969 0.48451289
 0.47215103 0.76066272 0.41604195 0.53013253 0.30483392 0.55223239
 0.48827906 0.66573854 0.36050943 0.91129225 0.55364527 0.39759669
 0.39759669 0.73521768]


In [12]:
def numerical_diff(
    f,
    x,
) -> float:
  h = 1e-50
  return (f(x + h) - f(x)) / h

In [13]:
def numerical_diff(
    f,
    x,
) -> float:
  h = 1e-4
  return (f(x + h) - f(x - h)) / (2 * h)

In [14]:
def func1(x):
  return 0.1 * (x ** 3) + x

In [15]:
numerical_diff(func1, 1)

1.3000000009999457

In [16]:
import numpy as np

def numerical_gradient(f, x) -> np.ndarray:
    grad = np.zeros_like(x)
    h = 1e-4

    # 원소의 값뿐만 아니라 인덱스(i)도 필요하므로 range를 사용합니다.
    for i in range(x.size):
        # 원본 값을 잠시 보관해둡니다.
        tmp_val = x[i]

        # 1. f(x + h) 계산 : i번째 원소만 h를 더하고 배열 전체를 f에 전달
        x[i] = tmp_val + h
        res1 = f(x)

        # 2. f(x - h) 계산 : i번째 원소만 h를 빼고 배열 전체를 f에 전달
        x[i] = tmp_val - h
        res2 = f(x)

        # 기울기(편미분) 계산 후 grad 배열의 i번째 자리에 저장
        grad[i] = (res1 - res2) / (2 * h)

        # 다음 원소 계산을 위해 원본 값으로 복원해둡니다.
        x[i] = tmp_val

    return grad

In [17]:
def func2(x):
  return x[0] ** 2 + x[1] ** 2

In [18]:
numerical_gradient(func2, np.array([3.0, 4.0]))

array([6., 8.])

In [35]:
def gradient_descent(
    func,
    init_x: float,
    learning_rate: float,
    step_num:int,
):
  x = init_x

  for i in range(step_num):
    grad = numerical_gradient(func, x)
    x -= learning_rate * grad
    print(grad)
    print(learning_rate * grad)
    print()

  return x

In [43]:
init_x = np.array([4., 4.])

res = gradient_descent(
    func = func2,
    init_x = init_x,
    learning_rate = 0.001,
    step_num = 100000,
    )

res

스트리밍 출력 내용이 길어서 마지막 5000줄이 삭제되었습니다.
[0. 0.]

[0. 0.]
[0. 0.]

[0. 0.]
[0. 0.]

[0. 0.]
[0. 0.]

[0. 0.]
[0. 0.]

[0. 0.]
[0. 0.]

[0. 0.]
[0. 0.]

[0. 0.]
[0. 0.]

[0. 0.]
[0. 0.]

[0. 0.]
[0. 0.]

[0. 0.]
[0. 0.]

[0. 0.]
[0. 0.]

[0. 0.]
[0. 0.]

[0. 0.]
[0. 0.]

[0. 0.]
[0. 0.]

[0. 0.]
[0. 0.]

[0. 0.]
[0. 0.]

[0. 0.]
[0. 0.]

[0. 0.]
[0. 0.]

[0. 0.]
[0. 0.]

[0. 0.]
[0. 0.]

[0. 0.]
[0. 0.]

[0. 0.]
[0. 0.]

[0. 0.]
[0. 0.]

[0. 0.]
[0. 0.]

[0. 0.]
[0. 0.]

[0. 0.]
[0. 0.]

[0. 0.]
[0. 0.]

[0. 0.]
[0. 0.]

[0. 0.]
[0. 0.]

[0. 0.]
[0. 0.]

[0. 0.]
[0. 0.]

[0. 0.]
[0. 0.]

[0. 0.]
[0. 0.]

[0. 0.]
[0. 0.]

[0. 0.]
[0. 0.]

[0. 0.]
[0. 0.]

[0. 0.]
[0. 0.]

[0. 0.]
[0. 0.]

[0. 0.]
[0. 0.]

[0. 0.]
[0. 0.]

[0. 0.]
[0. 0.]

[0. 0.]
[0. 0.]

[0. 0.]
[0. 0.]

[0. 0.]
[0. 0.]

[0. 0.]
[0. 0.]

[0. 0.]
[0. 0.]

[0. 0.]
[0. 0.]

[0. 0.]
[0. 0.]

[0. 0.]
[0. 0.]

[0. 0.]
[0. 0.]

[0. 0.]
[0. 0.]

[0. 0.]
[0. 0.]

[0. 0.]
[0. 0.]

[0. 0.]
[0. 0.]

[0. 0.]
[0. 0.]

[0. 0.]
[0. 0.]

[0.

array([6.76799177e-21, 6.76799177e-21])

In [21]:
func2(res)

np.float64(1.3278449820317862e-18)

In [22]:
def softmax(a):
  exp_a = np.exp(a)
  sum_exp_a = np.sum(exp_a)
  y = exp_a / sum_exp_a

  return y


In [23]:
class SimpleNet:

  def __init__(
      self,
  ):
    self.w = np.random.randn(2, 3)

  def predict(
      self,
      x,
  ):
    return np.dot(x, self.w)

  def loss(
      self,
      x,
      t,
  ):
    z = self.predict(x)
    y = softmax(z)
    loss = cross_entropy_error(y, t)

    return loss

In [24]:
simple_net = SimpleNet()
print(simple_net.w)

[[ 0.52439654  0.10636807  0.49529376]
 [ 0.68189339 -1.78357276 -0.82497397]]


In [25]:
x = np.array([1., 2.])

p = simple_net.predict(x)

print(p)

[ 1.88818332 -3.46077745 -1.15465418]


In [26]:
def sigmoid(x):
  return 1 / (1 + np.exp(-x))

In [27]:
import numpy as np

def numerical_gradient_ndim(f, x):
    h = 1e-4  # 0.0001
    grad = np.zeros_like(x)

    it = np.nditer(x, flags=['multi_index'], op_flags=['readwrite'])
    while not it.finished:
        idx = it.multi_index
        tmp_val = x[idx]

        x[idx] = float(tmp_val) + h
        fxh1 = f(x)

        x[idx] = float(tmp_val) - h
        fxh2 = f(x)

        grad[idx] = (fxh1 - fxh2) / (2 * h)

        x[idx] = tmp_val
        it.iternext()

    return grad

class TwoLayerNetwork:

  def __init__(
      self,
      input_size,
      hidden_size,
      output_size,
      weight_init_std=0.01,
  ):
    self.params = {}
    self.params['weight1'] = weight_init_std  * np.random.randn(input_size, hidden_size)
    self.params['weight2'] = weight_init_std  * np.random.randn(hidden_size, output_size)
    self.params['b1'] = np.zeros(hidden_size)
    self.params['b2'] = np.zeros(output_size)

  def predict(
      self,
      x,
  ):
    w1, w2 = self.params['weight1'], self.params['weight2']
    b1, b2 = self.params['b1'], self.params['b2']

    a1 = np.dot(x, w1) + b1

    z1 = sigmoid(a1)

    a2 = np.dot(z1, w2) + b2

    y = softmax(a2)

    return y

  def loss(
      self,
      x,
      t,
  ):
    y = self.predict(x)

    return cross_entropy_error(y, t)

  def accuracy(
      self,
      x,
      t,
  ):
    y = self.predict(x)
    y = np.argmax(y, axis=1)
    t = np.argmax(t, axis=1)

    accuracy = np.sum(y == t) / float(x.shape[0])

    return accuracy

  def numerical_gradient(self, x, t):
      # 외부 numerical_gradient_ndim 함수가 가중치를 바꿀 때마다
      # 새로운 가중치로 loss를 계산해주는 람다 함수
      loss_w = lambda W: self.loss(x, t)

      grads = {}
      # 호출하는 함수명을 numerical_gradient_ndim 으로 변경!
      grads['weight1'] = numerical_gradient_ndim(loss_w, self.params['weight1'])
      grads['b1']      = numerical_gradient_ndim(loss_w, self.params['b1'])
      grads['weight2'] = numerical_gradient_ndim(loss_w, self.params['weight2'])
      grads['b2']      = numerical_gradient_ndim(loss_w, self.params['b2'])

      return grads

In [28]:
network = TwoLayerNetwork(
    input_size=784,
    hidden_size=100,
    output_size=10,
)

In [29]:
# 100개 배치 대신, 딱 2개의 데이터만 넣어서 테스트!
x_small = np.random.rand(2, 784)
t_small = np.random.rand(2, 10)

# 이 상태로 돌리면 훨씬 빨리 끝납니다.
grads = network.numerical_gradient(x_small, t_small)
print("계산 완료!")

계산 완료!


In [30]:
# coding: utf-8
import os
import gzip
import pickle
import urllib.request
import numpy as np

# [수정] Yann LeCun 서버 불안정 문제를 해결하기 위해 미러링(Cloud) 서버 주소로 변경
url_base = 'https://ossci-datasets.s3.amazonaws.com/mnist/'
key_file = {
    'train_img':'train-images-idx3-ubyte.gz',
    'train_label':'train-labels-idx1-ubyte.gz',
    'test_img':'t10k-images-idx3-ubyte.gz',
    'test_label':'t10k-labels-idx1-ubyte.gz'
}

# [수정] 코랩 환경에는 __file__ 변수가 없으므로 기본 /content 경로로 설정합니다.
dataset_dir = "/content"
save_file = os.path.join(dataset_dir, "mnist.pkl")

train_num = 60000
test_num = 10000
img_dim = (1, 28, 28)
img_size = 784


def _download(file_name):
    file_path = os.path.join(dataset_dir, file_name)

    if os.path.exists(file_path):
        return

    print("Downloading " + file_name + " ... ")
    # 코랩 환경에서 다운로드 차단을 막기 위해 User-Agent 헤더 추가
    headers = {'User-Agent': 'Mozilla/5.0'}
    req = urllib.request.Request(url_base + file_name, headers=headers)

    with urllib.request.urlopen(req) as response, open(file_path, 'wb') as out_file:
        out_file.write(response.read())
    print("Done")

def download_mnist():
    for v in key_file.values():
       _download(v)

def _load_label(file_name):
    file_path = os.path.join(dataset_dir, file_name)

    print("Converting " + file_name + " to NumPy Array ...")
    with gzip.open(file_path, 'rb') as f:
            labels = np.frombuffer(f.read(), np.uint8, offset=8)
    print("Done")

    return labels

def _load_img(file_name):
    file_path = os.path.join(dataset_dir, file_name)

    print("Converting " + file_name + " to NumPy Array ...")
    with gzip.open(file_path, 'rb') as f:
            data = np.frombuffer(f.read(), np.uint8, offset=16)
    data = data.reshape(-1, img_size)
    print("Done")

    return data

def _convert_numpy():
    dataset = {}
    dataset['train_img'] =  _load_img(key_file['train_img'])
    dataset['train_label'] = _load_label(key_file['train_label'])
    dataset['test_img'] = _load_img(key_file['test_img'])
    dataset['test_label'] = _load_label(key_file['test_label'])

    return dataset

def init_mnist():
    download_mnist()
    dataset = _convert_numpy()
    print("Creating pickle file ...")
    with open(save_file, 'wb') as f:
        pickle.dump(dataset, f, -1)
    print("Done!")

def _change_one_hot_label(X):
    T = np.zeros((X.size, 10))
    for idx, row in enumerate(T):
        row[X[idx]] = 1

    return T


def load_mnist(normalize=True, flatten=True, one_hot_label=False):
    """MNIST 데이터셋 읽기

    Parameters
    ----------
    normalize : 이미지의 픽셀 값을 0.0~1.0 사이의 값으로 정규화할지 정한다.
    one_hot_label :
        one_hot_label이 True면、레이블을 원-핫(one-hot) 배열로 돌려준다.
    flatten : 입력 이미지를 1차원 배열로 만들지를 정한다.

    Returns
    -------
    (훈련 이미지, 훈련 레이블), (시험 이미지, 시험 레이블)
    """
    if not os.path.exists(save_file):
        init_mnist()

    with open(save_file, 'rb') as f:
        dataset = pickle.load(f)

    if normalize:
        for key in ('train_img', 'test_img'):
            dataset[key] = dataset[key].astype(np.float32)
            dataset[key] /= 255.0

    if one_hot_label:
        dataset['train_label'] = _change_one_hot_label(dataset['train_label'])
        dataset['test_label'] = _change_one_hot_label(dataset['test_label'])

    if not flatten:
         for key in ('train_img', 'test_img'):
            dataset[key] = dataset[key].reshape(-1, 1, 28, 28)

    return (dataset['train_img'], dataset['train_label']), (dataset['test_img'], dataset['test_label'])


# ==========================================
# 실행 테스트 코드
# ==========================================
# 이제 아래 함수를 실행하면 코랩 내부로 다운로드부터 포맷팅까지 한 번에 끝납니다!
(x_train, t_train), (x_test, t_test) = load_mnist(normalize=True, flatten=True, one_hot_label=True)

print("\n데이터 다운로드 및 로드 성공!")
print("x_train 구조:", x_train.shape)
print("t_train 구조:", t_train.shape)

Done
Done
Done
Done
Converting train-images-idx3-ubyte.gz to NumPy Array ...
Done
Converting train-labels-idx1-ubyte.gz to NumPy Array ...
Done
Converting t10k-images-idx3-ubyte.gz to NumPy Array ...
Done
Converting t10k-labels-idx1-ubyte.gz to NumPy Array ...
Done
Creating pickle file ...
Done!

데이터 다운로드 및 로드 성공!
x_train 구조: (60000, 784)
t_train 구조: (60000, 10)


In [32]:
import numpy as np

(x_train, t_train), (x_test, t_test) = load_mnist(normalize=True, one_hot_label=True)

max_cnt = 15
train_size = x_train.shape[0]
batch_size = 10
lr = 0.1

network = TwoLayerNetwork(
    input_size = 784,
    hidden_size=50,
    output_size = 10,
)

train_loss_list = []
train_acc_list = []
test_acc_list = []

iter_per_epoch = max(train_size / batch_size, 1)

for index in range(max_cnt):
  batch_mask = np.random.choice(train_size, batch_size)
  x_batch = x_train[batch_mask]
  t_batch = t_train[batch_mask]

  grad = network.numerical_gradient(x_batch, t_batch)

  for key in ('weight1', 'b1', 'weight2', 'b2'):
    network.params[key] -= lr * grad[key]

  loss = network.loss(x_batch, t_batch)
  train_loss_list.append(loss)
  print(f"반복 {index:3d}회째 Loss: {train_loss_list[index]:.4f}")

  if index % iter_per_epoch == 0:
    train_acc = network.accuracy(x_train, t_train)
    test_acc = network.accuracy(x_test, t_test)
    train_acc_list.append(train_acc)
    test_acc_list.append(test_acc)
    print(f"반복 {index:3d}회째 Train Acc: {train_acc:.4f}, Test Acc: {test_acc:.4f}")


반복   0회째 Loss: 44.1956
반복   0회째 Train Acc: 0.0974, Test Acc: 0.0982
반복   1회째 Loss: 49.2672
반복   2회째 Loss: 43.3746
반복   3회째 Loss: 42.5407
반복   4회째 Loss: 44.0064
반복   5회째 Loss: 41.9799
반복   6회째 Loss: 44.0096
반복   7회째 Loss: 43.8856
반복   8회째 Loss: 43.6120
반복   9회째 Loss: 42.8583
반복  10회째 Loss: 44.0333
반복  11회째 Loss: 45.6884
반복  12회째 Loss: 44.9714
반복  13회째 Loss: 44.8358
반복  14회째 Loss: 44.7222
